server:
  tomcat:
    uri-encoding: UTF-8
  port: 1902
spring:
  profiles:
    active: dev
  application:
    name: kafka-consumer-server
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
